# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI to DockerHub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js v14.18.2
      uses: actions/setup-node@v2
      with:
        node-version: '14.18.2'
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test -- --coverage 

  
    - name: Checkout Latest Repo
      uses: actions/checkout@master

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Publish to DockerHub
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: latest, ${{ github.run_number }}
      
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}


    